version: "3.8"
services:
#  demo-kotlin:
#    depends_on:
#      - kotlin-postgres
#    ports:
#      - 9000:9000
#      - 8000:8000
#    environment:
#      - BPL_JVM_THREAD_COUNT=50
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://router-postgres:5432/kotlin
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8000
  kotlin-postgres:
    image: "postgres:14.4"
    container_name: "kotlin-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2
      - POSTGRES_DB=kotlin